# 
# Copyright (c) 2006-2016 Frans Kaashoek, Robert Morris, Russ Cox,
#                         Massachusetts Institute of Technology
# Copyright (c) 2016 Simon Schmidt
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# run as: ruby intvec.rb > intvec.s

puts("# 
# Copyright (c) 2006-2016 Frans Kaashoek, Robert Morris, Russ Cox,
#                         Massachusetts Institute of Technology
# Copyright (c) 2016 Simon Schmidt
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the \"Software\"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# generated by intvec.rb - do not edit

# handlers
")

has = {}
has[8]  = true
has[17] = true
has[30] = true
(10..14).each{|x| has[x]=true}

puts(".text")
puts(".global __i686_isr")
(0..255).each{ |i|
	puts("__i686_vector_#{i}:")
	if not has[i] then
		puts("  pushl $0")
	end
	puts("  pushl $#{i}")
	puts("  jmp __i686_isr")
	puts("")
}
puts("")
puts("# vector table")
puts(".section .rodata")
puts(".global __i686_vectors")
puts("__i686_vectors:")
(0..255).each{ |i|
	puts("  .long __i686_vector_#{i}")
}
puts("")
puts("")
